/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.EntityManager;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

import logica.controlador.Fabrica;
import logica.controlador.IControlador;


import logica.datatypes.DtCuponera;

/**
 *
 * @author elinzar
 */
import logica.datatypes.DtInstitucion;
public class AgregarActividadDeportivaCuponera extends javax.swing.JFrame {

	
	VentanaMensaje msj;
    /**
     * Creates new form AgregarActividadDeportivaCuponera
     */
    public AgregarActividadDeportivaCuponera() {
        initComponents();
        //Call Backend
        Fabrica f = new Fabrica();
        IControlador sistema = f.getInterface();
        //Fetch Cuponeras and Instituciones
        ArrayList<String> ListaCuponeras = sistema.getNombreCuponeras();
        ArrayList<String> ListaInstitucion = sistema.getNombreInstituciones();
        
        //Set first null combobox member
        String [] CuponeraList = new String[ListaCuponeras.size()+1];
        String [] InstitucionList = new String[ListaInstitucion.size()+1];
        CuponeraList[0] = "-";
        InstitucionList[0] = "-";
        int c = 1;
        int i = 1;
        for (String DtCup : ListaCuponeras){
            
            CuponeraList[c] = DtCup;
            c++;        
        }
        for (String DtInst : ListaInstitucion){
            
            InstitucionList[i] = DtInst;
            i++;        
        }
                
        this.SelCuponeraCB.setModel(new DefaultComboBoxModel(CuponeraList));
        this.SelInstitucionCB.setModel(new DefaultComboBoxModel(InstitucionList));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SelCuponeraCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        SelInstitucionCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ActividadesDeportivasLS = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        CantidadClasesTF = new javax.swing.JTextField();
        GuardarBT = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ActividadesEnCuponerasLS = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Actividad Deportiva A Cuponera");

        jLabel2.setText("Seleccionar Cuponera:");

        SelCuponeraCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelCuponeraCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelCuponeraCBActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccionar Institucion:");

        SelInstitucionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelInstitucionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelInstitucionCBActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ActividadesDeportivasLS);

        jLabel4.setText("Cantidad de Clases:");

        GuardarBT.setText("Guardar");
        GuardarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBTActionPerformed(evt);
            }
        });

        jLabel5.setText("Actividades Deportivas:");

        jLabel6.setText("Actividades en Cuponeras:");

        jScrollPane3.setViewportView(ActividadesEnCuponerasLS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelCuponeraCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SelInstitucionCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CantidadClasesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuardarBT))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SelCuponeraCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SelInstitucionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CantidadClasesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(GuardarBT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelCuponeraCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelCuponeraCBActionPerformed
        this.ListarActis();
    }//GEN-LAST:event_SelCuponeraCBActionPerformed

    private void SelInstitucionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelInstitucionCBActionPerformed
        this.ListarActis();
    }//GEN-LAST:event_SelInstitucionCBActionPerformed

    private void GuardarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBTActionPerformed
        
        //Set Backend Access
        Fabrica f = new Fabrica();
        IControlador sistema = f.getInterface();
        //prepare data to send into backend
        //cuponera
        System.out.println("In Menu AgregarActis");
        System.out.println(this.SelCuponeraCB.getSelectedItem().toString());
        String nombreCup = this.SelCuponeraCB.getSelectedItem().toString();
        //actividad
        System.out.println(this.ActividadesDeportivasLS.getSelectedValue());
        String nombreActi = this.ActividadesDeportivasLS.getSelectedValue();
        
        //error check that cant classes isnt a string type object but a proper Integer
        System.out.println(this.CantidadClasesTF.getText());
        int cantClasses = 0;
        boolean success = false;
        try{
            cantClasses = Integer.parseInt(this.CantidadClasesTF.getText());
            
            success = true;
           }
        catch (NumberFormatException ex){
            success = false;
            System.out.println("Error!");
            //ToDo show error message to Client
        }
        if(success == true){
            //Call backend, send data
        	try {
        		sistema.agregarActividadCuponera(nombreCup,nombreActi,cantClasses);
        		this.ListarActis();
        		
        	}catch (IllegalArgumentException e) {
        		System.out.println(e.getMessage());
			}
        }else {
        	msj = new VentanaMensaje("Error", "Formato de numero invalido", Color.RED); 
        	msj.setVisible(true);
        }
        
    }//GEN-LAST:event_GuardarBTActionPerformed
    
    private void ListarActis(){
        //Check if Selection is valid
        if(this.SelCuponeraCB.getSelectedIndex() == 0 || this.SelInstitucionCB.getSelectedIndex() == 0){
            System.out.println("Index 0 Selected");
            String [] Empty = new String [] {""};
            this.ActividadesDeportivasLS.setListData(Empty);
        }
        else
        {
            //Fetch Selection
            String CupCBSelection = this.SelCuponeraCB.getSelectedItem().toString();
            System.out.print("CupCBSelection :");
            System.out.println(CupCBSelection);
            String InstiCBSelection = this.SelInstitucionCB.getSelectedItem().toString();
            System.out.print("InstiCBSelection :");
            System.out.println(InstiCBSelection);
            
            //Selection Fetched, Call backend
            Fabrica f = new Fabrica();
            IControlador sistema = f.getInterface();
            
            //Get Data from Backend for Instis
            ArrayList<String> InstiCBSelectionActis = sistema.consultarActividadDepo(InstiCBSelection);
            System.out.print("Size of InstiCBSelectionActis = ");
            System.out.println(InstiCBSelectionActis.size());  
            
            //Get Data from Backend for Cuponeras
            ArrayList <String> ActisDeCup = sistema.getActisDeCuponera(CupCBSelection);
            String[] listActisDeCup = new String [ActisDeCup.size()] ;
            int i = 0;
            for(String acti : ActisDeCup){
                listActisDeCup[i] = acti;
            }
            this.ActividadesEnCuponerasLS.setListData(listActisDeCup);
            System.out.print("Size of ActisDeCup = ");
            System.out.println(ActisDeCup.size());   
            
            //Compare Actis, Delete Overlapping Actis from Set
            i = 0;
            if(!ActisDeCup.isEmpty()){
                Collection<String> objectsToRemove = new ArrayList<>();
                
                for(String InstiActis : InstiCBSelectionActis){
                    System.out.println(InstiActis); 
                    boolean t = ActisDeCup.contains(InstiActis);
                    System.out.print("Actis De Cup True?: ");
                    System.out.println(t);
                    if(t == true){
                        objectsToRemove.add(InstiActis);
                    }
                    i++;
                }
                if(!objectsToRemove.isEmpty()){
                    InstiCBSelectionActis.removeAll(objectsToRemove);
                }
            }
            
            //Prepare String Array for Listing
            i = 0; //reused
            String [] ActiList = new String [InstiCBSelectionActis.size()];
            for(String InstiActis : InstiCBSelectionActis){
                System.out.println(InstiActis);
                ActiList[i] = InstiActis;
               i++;
            }
            //List Actis into JList
            this.ActividadesDeportivasLS.setListData(ActiList);
        }   
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AgregarActividadDeportivaCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AgregarActividadDeportivaCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AgregarActividadDeportivaCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AgregarActividadDeportivaCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgregarActividadDeportivaCuponera().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ActividadesDeportivasLS;
    private javax.swing.JList<String> ActividadesEnCuponerasLS;
    private javax.swing.JTextField CantidadClasesTF;
    private javax.swing.JButton GuardarBT;
    private javax.swing.JComboBox<String> SelCuponeraCB;
    private javax.swing.JComboBox<String> SelInstitucionCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
