package gui;
import logica.datatypes.DtCuponera;

import java.text.Format;

import logica.datatypes.DtClase;

public class VentanaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsulta
     */
    public VentanaConsulta() {
        initComponents();
    }
    
    public VentanaConsulta(Object DtAUsar){
        initComponents();
        
        if(DtAUsar.getClass().equals(DtCuponera.class)) {
        	DtCuponera cupo = ((DtCuponera) DtAUsar);
        	this.labelTitulo.setText("Consulta de Cuponera");
        	this.label1.setText("Nombre :" + cupo.nombreCup);
        	this.label2.setText("Descripcion: " + cupo.descripcion);
        	this.label3.setText("Cant. clases: "+ cupo.cantClases);
        	this.label4.setText("Descuento: " + cupo.descuento + "%");
        	this.label5.setText("Fecha de Inicio: " + cupo.fechaInicio);
        	this.label6.setText("Fecha de Fin: " + cupo.fechaFin);
        	this.label7.setText("Fecha de Alta: " + cupo.fechaAlta);

        	
        }else {
        	DtClase clase = ((DtClase) DtAUsar);
        	this.labelTitulo.setText("Consulta de Clase");
        	this.label1.setText("Nombre :" + clase.nombreClase);
        	this.label2.setText("Cantidad minima Socios: " + clase.cantMin);
        	this.label3.setText("Cantidad maxima Socios: "+ clase.cantMax);
        	this.label4.setText("Fecha " + clase.fecha );
        	this.label5.setText("Hora Inicio: " + clase.horaIni);
        	this.label6.setText("Fecha de Registro: " + clase.fechaRegistro);
        	this.label7.setText("URL: " + clase.claseURL);
        	;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAzul = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        botonSalida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAzul.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelTitulo.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        labelTitulo.setText("titulo");

        label1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label1.setText("jLabel2");

        label2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label2.setText("jLabel3");

        label3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label3.setText("jLabel4");

        label4.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label4.setText("jLabel5");

        label5.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label5.setText("jLabel6");

        label6.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label6.setText("jLabel7");

        label7.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label7.setText("jLabel8");

        botonSalida.setBackground(new java.awt.Color(255, 51, 51));
        botonSalida.setText("<---------");
        botonSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalidaMouseClicked(evt);
            }
        });
        botonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalida)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addComponent(label4)
                            .addComponent(label1)
                            .addComponent(label2)
                            .addComponent(label3)
                            .addComponent(label7)
                            .addComponent(label6)
                            .addComponent(label5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(panelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label2)
                .addGap(12, 12, 12)
                .addComponent(label3)
                .addGap(12, 12, 12)
                .addComponent(label4)
                .addGap(12, 12, 12)
                .addComponent(label5)
                .addGap(12, 12, 12)
                .addComponent(label6)
                .addGap(12, 12, 12)
                .addComponent(label7)
                .addGap(24, 24, 24)
                .addComponent(botonSalida)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalidaMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_botonSalidaMouseClicked

    private void botonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalidaActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaConsulta().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalida;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelAzul;
    // End of variables declaration//GEN-END:variables
}
