package gui;


public class AltaClase extends javax.swing.JFrame {

    /**
     * Creates new form AltaClase
     */
    public AltaClase() {
        initComponents();
        
        this.labelFechaFin.setVisible(false);
        this.labelFechaIni.setVisible(false);
        this.labelMMDDAA1.setVisible(false);
        this.labelMMDDAA2.setVisible(false);
        this.labelMax.setVisible(false);
        this.labelMin.setVisible(false);
        this.labelSocios.setVisible(false);
            
        this.spinnerFechaFin.setVisible(false);
        this.spinnerFechaIni.setVisible(false);
        this.spinnerMax.setVisible(false);
        this.spinnerMin.setVisible(false);
           
        this.textNombreClase.setVisible(false);
        this.textNombreProfe.setVisible(false);
        this.textURL.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        comboInsti = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        spinnerFechaIni = new javax.swing.JSpinner();
        textNombreClase = new javax.swing.JTextField();
        textNombreProfe = new javax.swing.JTextField();
        labelSocios = new javax.swing.JLabel();
        spinnerMin = new javax.swing.JSpinner();
        spinnerMax = new javax.swing.JSpinner();
        labelMin = new javax.swing.JLabel();
        labelMax = new javax.swing.JLabel();
        textURL = new javax.swing.JTextField();
        spinnerFechaFin = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        labelMMDDAA1 = new javax.swing.JLabel();
        labelMMDDAA2 = new javax.swing.JLabel();
        labelFechaIni = new javax.swing.JLabel();
        labelFechaFin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setText("Alta de dictado de Clase");

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("<---------");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        comboInsti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboInsti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInstiActionPerformed(evt);
            }
        });

        jLabel3.setText("Institución");

        spinnerFechaIni.setModel(new javax.swing.SpinnerDateModel());

        textNombreClase.setText("Escriba el nombre de la clase");
        textNombreClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textNombreClaseMouseClicked(evt);
            }
        });
        textNombreClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreClaseActionPerformed(evt);
            }
        });

        textNombreProfe.setText("Escriba el nombre del profesor");
        textNombreProfe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textNombreProfeMouseClicked(evt);
            }
        });
        textNombreProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreProfeActionPerformed(evt);
            }
        });

        labelSocios.setText("Socios:");

        spinnerMin.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        spinnerMax.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        labelMin.setText("min");

        labelMax.setText("max");

        textURL.setText("Escriba la URL asociada");
        textURL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textURLMouseClicked(evt);
            }
        });
        textURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textURLActionPerformed(evt);
            }
        });

        spinnerFechaFin.setModel(new javax.swing.SpinnerDateModel());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        botonAceptar.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAceptarMouseClicked(evt);
            }
        });
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelMMDDAA1.setText("MM/DD/AA");

        labelMMDDAA2.setText("MM/DD/AA");

        labelFechaIni.setText("fecha inicio");

        labelFechaFin.setText("fecha fin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNombreProfe)
                                    .addComponent(textURL))
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelSocios)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnerMin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelMin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spinnerMax, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelMax))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(spinnerFechaFin, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spinnerFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelMMDDAA2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelFechaFin))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelMMDDAA1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelFechaIni))))
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboInsti, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(textNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboInsti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(textNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMMDDAA1)
                    .addComponent(labelFechaIni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMMDDAA2)
                    .addComponent(labelFechaFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNombreProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSocios)
                    .addComponent(spinnerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMin)
                    .addComponent(labelMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void textNombreClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreClaseActionPerformed

    private void textURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textURLActionPerformed

    private void botonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked

    }//GEN-LAST:event_botonAceptarMouseClicked

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void textNombreProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreProfeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreProfeActionPerformed

    private void comboInstiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInstiActionPerformed
        if(this.comboInsti.getSelectedIndex() != 0){
            this.labelFechaFin.setVisible(true);
            this.labelFechaIni.setVisible(true);
            this.labelMMDDAA1.setVisible(true);
            this.labelMMDDAA2.setVisible(true);
            this.labelMax.setVisible(true);
            this.labelMin.setVisible(true);
            this.labelSocios.setVisible(true);
            
            this.spinnerFechaFin.setVisible(true);
            this.spinnerFechaIni.setVisible(true);
            this.spinnerMax.setVisible(true);
            this.spinnerMin.setVisible(true);
            
            this.textNombreClase.setVisible(true);
            this.textNombreProfe.setVisible(true);
            this.textURL.setVisible(true);
        }else{
            this.labelFechaFin.setVisible(false);
            this.labelFechaIni.setVisible(false);
            this.labelMMDDAA1.setVisible(false);
            this.labelMMDDAA2.setVisible(false);
            this.labelMax.setVisible(false);
            this.labelMin.setVisible(false);
            this.labelSocios.setVisible(false);
            
            this.spinnerFechaFin.setVisible(false);
            this.spinnerFechaIni.setVisible(false);
            this.spinnerMax.setVisible(false);
            this.spinnerMin.setVisible(false);
            
            this.textNombreClase.setVisible(false);
            this.textNombreProfe.setVisible(false);
            this.textURL.setVisible(false);
        }
    }//GEN-LAST:event_comboInstiActionPerformed

    private void textNombreClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNombreClaseMouseClicked
        if(this.textNombreClase.getText().equals("Escriba el nombre de la clase")){
            this.textNombreClase.setText("");
        }
    }//GEN-LAST:event_textNombreClaseMouseClicked

    private void textNombreProfeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNombreProfeMouseClicked
        if(this.textNombreProfe.getText().equals("Escriba el nombre del profesor")){
            this.textNombreProfe.setText("");
        }
    }//GEN-LAST:event_textNombreProfeMouseClicked

    private void textURLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textURLMouseClicked
        if(this.textURL.getText().equals("Escriba la URL asociada")){
            this.textURL.setText("");
        }
    }//GEN-LAST:event_textURLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaClase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JComboBox<String> comboInsti;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFechaFin;
    private javax.swing.JLabel labelFechaIni;
    private javax.swing.JLabel labelMMDDAA1;
    private javax.swing.JLabel labelMMDDAA2;
    private javax.swing.JLabel labelMax;
    private javax.swing.JLabel labelMin;
    private javax.swing.JLabel labelSocios;
    private javax.swing.JSpinner spinnerFechaFin;
    private javax.swing.JSpinner spinnerFechaIni;
    private javax.swing.JSpinner spinnerMax;
    private javax.swing.JSpinner spinnerMin;
    private javax.swing.JTextField textNombreClase;
    private javax.swing.JTextField textNombreProfe;
    private javax.swing.JTextField textURL;
    // End of variables declaration//GEN-END:variables
}
