package gui;

import java.util.Date;

import javax.persistence.EntityManager;

import java.io.File;
import java.time.LocalDateTime;
import java.time.ZoneId;
import logica.controlador.IControlador;
import logica.controlador.Fabrica;
import java.util.ArrayList;

public class AltaActividadDeportiva extends javax.swing.JFrame {
	

    public LocalDateTime convertirALocalDateTime(Date dateAConvertir){
        return dateAConvertir.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
    }
    
    /**
     * Creates new form AltaActividadDeportiva
     */
    public AltaActividadDeportiva() {
        Fabrica fab = new Fabrica();
        IControlador controlador = fab.getInterface();
        
        initComponents();
        
        ArrayList<String> arrStr = controlador.getNombreInstituciones();
        
        for(int i = 0; i < arrStr.size();i++){
            this.comboInsti.addItem(arrStr.get(i));
        }
        
        
            //----------------escondo labels----------------------------
            this.lblNombre.setVisible(false);
            this.lblDesc.setVisible(false);
            this.lblDura.setVisible(false);
            this.lblURL.setVisible(false);
            this.lblCosto.setVisible(false);
            this.lblMMDDAA.setVisible(false);
            //----------------escondo los fields---------------------------
            this.fieldDesc.setVisible(false);
            this.fieldDuracion.setVisible(false);
            this.fieldNombre.setVisible(false);
            this.textIMG.setVisible(false);
            //----------------escondo los spinners---------------------------
            this.spinnerCosto.setVisible(false);
            this.spinnerFecha.setVisible(false);

            
    }
    
//     public AltaActividadDeportiva(IControlador controlador) {
////        Fabrica fab = new Fabrica();
////        IControlador controlador = fab.getInterface();
//        
//        initComponents();
//    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        fieldNombre = new javax.swing.JTextField();
        fieldDesc = new javax.swing.JTextField();
        fieldDuracion = new javax.swing.JTextField();
        spinnerCosto = new javax.swing.JSpinner();
        lblCosto = new javax.swing.JLabel();
        spinnerFecha = new javax.swing.JSpinner();
        lblMMDDAA = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        textIMG = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblDura = new javax.swing.JLabel();
        lblURL = new javax.swing.JLabel();
        comboInsti = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setText("Dar de alta Actividad Deportiva");

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jButton1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fieldNombre.setText("Escriba el nombre");
        fieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldNombreMouseClicked(evt);
            }
        });
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });

        fieldDesc.setText("Escriba la descripción");
        fieldDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldDescMouseClicked(evt);
            }
        });
        fieldDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescActionPerformed(evt);
            }
        });

        fieldDuracion.setText("Escriba la duración");
        fieldDuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldDuracionMouseClicked(evt);
            }
        });
        fieldDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDuracionActionPerformed(evt);
            }
        });

        spinnerCosto.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lblCosto.setText("Costo $");

        spinnerFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1661233467001L), null, null, java.util.Calendar.DAY_OF_YEAR));

        lblMMDDAA.setText("MM/DD/AA");

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("<---------");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        textIMG.setText("Escriba la URL de la imagen");
        textIMG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textIMGMouseClicked(evt);
            }
        });
        textIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIMGActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        lblDesc.setText("Descripción");

        lblDura.setText("Duración");

        lblURL.setText("URL IMG");

        comboInsti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        comboInsti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInstiActionPerformed(evt);
            }
        });

        jLabel2.setText("Institución");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboInsti, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spinnerFecha)
                                    .addComponent(spinnerCosto)
                                    .addComponent(textIMG, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(fieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldDesc, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldDuracion, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDura)
                                    .addComponent(lblNombre)
                                    .addComponent(lblMMDDAA)
                                    .addComponent(lblCosto)
                                    .addComponent(lblDesc)
                                    .addComponent(lblURL)
                                    .addComponent(jLabel2))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboInsti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMMDDAA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCosto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblURL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void fieldDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescActionPerformed

    private void fieldDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDuracionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldNombreMouseClicked
        if(fieldNombre.getText().equals("Escriba el nombre")){
            fieldNombre.setText("");
        }
    }//GEN-LAST:event_fieldNombreMouseClicked

    private void fieldDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldDescMouseClicked
        if(fieldDesc.getText().equals("Escriba la descripción")){
            fieldDesc.setText("");
        }
    }//GEN-LAST:event_fieldDescMouseClicked

    private void fieldDuracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldDuracionMouseClicked
        if(fieldDuracion.getText().equals("Escriba la duración")){
            fieldDuracion.setText("");
        }
    }//GEN-LAST:event_fieldDuracionMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nombreActividad = fieldNombre.getText();
        String nombreInsti = this.comboInsti.getSelectedItem().toString();
        String desc = fieldDesc.getText();
        
        try{//se intenta parsear el float
            float dura = Float.parseFloat(fieldDuracion.getText());
            
            System.out.println(dura);
            
            float costo = Float.parseFloat(spinnerCosto.getValue().toString());
            LocalDateTime fechaAlta = convertirALocalDateTime(((Date)spinnerFecha.getValue()));
            String URL_IMG = this.textIMG.getText();
            
            Fabrica fab = new Fabrica();
            IControlador controlador =  fab.getInterface();
            
            try{//se intenta persistir los datos
                controlador.altaActividadDepo(nombreActividad,nombreInsti,desc,dura,costo,fechaAlta);
                
            }catch(Exception e){//algo malió sal en la persistición
                VentanaMensaje errorVentana = new VentanaMensaje("ERROR!",e.getMessage(),java.awt.Color.RED);
                errorVentana.setVisible(true);
                return;
            }
            
        }catch(Exception e){//fallo el parseo del float
            VentanaMensaje errorVentana = new VentanaMensaje("ERROR!","caracteres invalidos en campo Duracion",java.awt.Color.RED);
            errorVentana.setVisible(true);
            return;
        }
        
        VentanaMensaje ventanaSatisfactoria = new VentanaMensaje("Actividad Deportiva","Se dio de alta la actividad satisfactoriamente",java.awt.Color.green);
        ventanaSatisfactoria.setVisible(true);
        
        
         
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIMGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIMGActionPerformed

    private void textIMGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textIMGMouseClicked
        // TODO add your handling code here:
        if(this.textIMG.getText().equals("Escriba la URL de la imagen")){
            this.textIMG.setText("");
        }
    }//GEN-LAST:event_textIMGMouseClicked

    private void comboInstiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInstiActionPerformed
        // TODO add your handling code here:
        if(this.comboInsti.getSelectedIndex() != 0){
            //----------------muestro labels----------------------------
            this.lblNombre.setVisible(true);
            this.lblDesc.setVisible(true);
            this.lblDura.setVisible(true);
            this.lblURL.setVisible(true);
            this.lblCosto.setVisible(true);
            this.lblMMDDAA.setVisible(true);
            //----------------muestro los fields---------------------------
            this.fieldDesc.setVisible(true);
            this.fieldDuracion.setVisible(true);
            this.fieldNombre.setVisible(true);
            this.textIMG.setVisible(true);
            //----------------muestro los spinners-----------------------
            this.spinnerCosto.setVisible(true);
            this.spinnerFecha.setVisible(true);
            
            
        }else{
            //----------------escondo labels----------------------------
            this.lblNombre.setVisible(false);
            this.lblDesc.setVisible(false);
            this.lblDura.setVisible(false);
            this.lblURL.setVisible(false);
            this.lblCosto.setVisible(false);
            this.lblMMDDAA.setVisible(false);
            //----------------escondo los fields---------------------------
            this.fieldDesc.setVisible(false);
            this.fieldDuracion.setVisible(false);
            this.fieldNombre.setVisible(false);
            this.textIMG.setVisible(false);
            //----------------escondo los spinners---------------------------
            this.spinnerCosto.setVisible(false);
            this.spinnerFecha.setVisible(false);
            
        }
    }//GEN-LAST:event_comboInstiActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AltaActividadDeportiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AltaActividadDeportiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AltaActividadDeportiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AltaActividadDeportiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AltaActividadDeportiva(em).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboInsti;
    private javax.swing.JTextField fieldDesc;
    private javax.swing.JTextField fieldDuracion;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDura;
    private javax.swing.JLabel lblMMDDAA;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblURL;
    private javax.swing.JSpinner spinnerCosto;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JTextField textIMG;
    // End of variables declaration//GEN-END:variables
}
