/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import logica.clase.Clase;
import logica.controlador.Fabrica;
import logica.controlador.IControlador;
import logica.datatypes.DtActividadDeportiva;
import logica.datatypes.DtProfesor;
import logica.datatypes.DtSocio;
import logica.datatypes.DtUsrKey;
import logica.datatypes.DtUsuario;
import logica.usuario.*;


/**
 *
 * @author elinzar
 */
public class ConsultaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaUsuario
     */
    private ArrayList<DtUsrKey> UsrKeys;
    
    public ConsultaUsuario() {
        initComponents();
        Fabrica f = new Fabrica();
	IControlador sistema = f.getInterface();
        UsrKeys = sistema.listarUsuarios();
	String[] arrayKeys = new String[UsrKeys.size()];
	int i = 0;
	for (DtUsrKey keyUsr : UsrKeys) {
		arrayKeys[i] = keyUsr.nickname;
		i++;
	}
        this.UsuariosjList.setListData(arrayKeys);
        this.ClasesProfeCB.setEnabled(false);
        this.BiografiaProfeTA.setEnabled(false);
        this.DescripcionProfeTA.setEnabled(false);
        this.SitioWebTF.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nomActiTFJ2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        descTAJ2 = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        duracionTFJ2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        costoTFJ2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        fechaRegTFJ2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        clasesActiJLJ2 = new javax.swing.JList<>();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        cuponerasActiJLJ2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NicknameTF = new javax.swing.JTextField();
        NombeTF = new javax.swing.JTextField();
        ApellidoTF = new javax.swing.JTextField();
        EmailTF = new javax.swing.JTextField();
        FechaNacimientoTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        UsuariosjList = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UrlImagenTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescripcionProfeTA = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BiografiaProfeTA = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        SitioWebTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ClasesProfeCB = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        ActividadDepoAsociadaTF = new javax.swing.JTextField();
        ActividadDepoAsociadaBT = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        clasesRegSocioCB = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nomClassTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        fechaInicioTF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        horaInicioTF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        horaFinTF = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        minRegistrosTF = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        maxRegistrosTF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cantRegistrosTF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        fechaAltaTF = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        urlClassTF = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        jLabel19.setText("jLabel19");


        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFrame1.setMinimumSize(new java.awt.Dimension(400, 453));
        jFrame1.setResizable(false);

        jLabel28.setText("Informacion Actividad Deportiva");

        jLabel29.setText("Nombre:");

        nomActiTFJ2.setEditable(false);

        jLabel30.setText("Descripcion:");

        descTAJ2.setEditable(false);
        descTAJ2.setColumns(20);
        descTAJ2.setLineWrap(true);
        descTAJ2.setRows(5);
        descTAJ2.setWrapStyleWord(true);
        jScrollPane4.setViewportView(descTAJ2);

        jLabel31.setText("Duracion:");

        duracionTFJ2.setEditable(false);
        duracionTFJ2.setText("jTextField2");

        jLabel32.setText("Costo:");

        costoTFJ2.setEditable(false);
        costoTFJ2.setText("jTextField3");

        jLabel33.setText("Fecha Alta:");

        fechaRegTFJ2.setEditable(false);
        fechaRegTFJ2.setText("jTextField4");

        jLabel34.setText("Clases:");

        clasesActiJLJ2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(clasesActiJLJ2);

        jLabel35.setText("Cuponeras:");

        cuponerasActiJLJ2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(cuponerasActiJLJ2);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(89, 89, 89))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomActiTFJ2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(duracionTFJ2)
                    .addComponent(costoTFJ2)
                    .addComponent(fechaRegTFJ2)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(nomActiTFJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(12, 12, 12)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(duracionTFJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(costoTFJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(fechaRegTFJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);


        jLabel3.setText("Nickname:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Apellido:");

        jLabel6.setText("Email:");

        jLabel7.setText("Fecha de Nacimiento:");

        NicknameTF.setEditable(false);

        NombeTF.setEditable(false);

        ApellidoTF.setEditable(false);

        EmailTF.setEditable(false);

        FechaNacimientoTF.setEditable(false);

        UsuariosjList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                UsuariosjListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(UsuariosjList);

        jLabel9.setText("Lista de Usuarios:");

        jLabel2.setText("Url Imagen:");

        UrlImagenTF.setEditable(false);

        jLabel1.setText("Profesor:");

        jLabel8.setText("Descripcion General:");

        DescripcionProfeTA.setEditable(false);
        DescripcionProfeTA.setColumns(20);
        DescripcionProfeTA.setLineWrap(true);
        DescripcionProfeTA.setRows(5);
        DescripcionProfeTA.setWrapStyleWord(true);
        jScrollPane2.setViewportView(DescripcionProfeTA);

        jLabel10.setText("Biografia:");

        BiografiaProfeTA.setEditable(false);
        BiografiaProfeTA.setColumns(20);
        BiografiaProfeTA.setLineWrap(true);
        BiografiaProfeTA.setRows(5);
        BiografiaProfeTA.setWrapStyleWord(true);
        jScrollPane3.setViewportView(BiografiaProfeTA);

        jLabel11.setText("Sitio Web:");

        SitioWebTF.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel13.setText("Consulta Usuario");

        jLabel14.setText("Socio:");

        jLabel15.setText("Clases que Dicta:");

        ClasesProfeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClasesProfeCBActionPerformed(evt);
            }
        });

        jLabel12.setText("Actividad Deportiva Asociada a Clase:");

        ActividadDepoAsociadaTF.setEditable(false);
        ActividadDepoAsociadaTF.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        ActividadDepoAsociadaBT.setText("Mostrar Mas Informacion");
        ActividadDepoAsociadaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActividadDepoAsociadaBTActionPerformed(evt);
            }
        });

        jLabel16.setText("Clases Registradas:");

        jLabel17.setText("Informacion de Clase:");

        jLabel18.setText("Nombre:");

        jLabel20.setText("Fecha de Inicio:");

        jLabel21.setText("Hora de Inicio:");

        jLabel22.setText("Hora de Fin:");

        jLabel23.setText("Min Registros:");

        jLabel24.setText("Max Registros:");

        jLabel25.setText("Cant Registros:");

        jLabel26.setText("Fecha de Alta:");

        jLabel27.setText("URL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NicknameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NombeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ApellidoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FechaNacimientoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(UrlImagenTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ActividadDepoAsociadaTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ClasesProfeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SitioWebTF))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel12)
                                    .addComponent(ActividadDepoAsociadaBT))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clasesRegSocioCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel27))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(horaInicioTF)
                                            .addComponent(fechaInicioTF)
                                            .addComponent(nomClassTF)
                                            .addComponent(horaFinTF)
                                            .addComponent(minRegistrosTF)
                                            .addComponent(maxRegistrosTF)
                                            .addComponent(cantRegistrosTF)
                                            .addComponent(fechaAltaTF)
                                            .addComponent(urlClassTF))))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(319, 319, 319))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NicknameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ApellidoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaNacimientoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UrlImagenTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clasesRegSocioCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(nomClassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(fechaInicioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(horaInicioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(horaFinTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(minRegistrosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(maxRegistrosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(cantRegistrosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(fechaAltaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urlClassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)))
                    .addComponent(ActividadDepoAsociadaBT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(SitioWebTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClasesProfeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ActividadDepoAsociadaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuariosjListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_UsuariosjListValueChanged
        System.out.println("listValueChanged");
        //set Backend Access
        Fabrica f = new Fabrica();
	IControlador sistema = f.getInterface();
        
        insti = null;
        
        DtUsrKey usrKey = null;
        
        for (DtUsrKey key : this.UsrKeys) {
            if(key.nickname.equals(this.UsuariosjList.getSelectedValue()) == true){
                usrKey = key;
                break;
            }
            
        }
        if(usrKey != null){
            DtUsuario DtUsr = sistema.getDatosUsuario(usrKey);
        
            this.ApellidoTF.setText(DtUsr.apellido);
            this.EmailTF.setText(DtUsr.email);
            this.FechaNacimientoTF.setText(DtUsr.fechaNac.toString());
            this.NicknameTF.setText(DtUsr.nickname);
            this.NombeTF.setText(DtUsr.nombre);
            this.UrlImagenTF.setText(DtUsr.imagenUrl);
            
            if(DtUsr instanceof DtProfesor){
                
                this.BiografiaProfeTA.setEnabled(true);
                this.DescripcionProfeTA.setEnabled(true);
                this.SitioWebTF.setEnabled(true);
                
                this.BiografiaProfeTA.setText(((DtProfesor) DtUsr).biografia);
                this.DescripcionProfeTA.setText(((DtProfesor) DtUsr).descripcion);
                this.SitioWebTF.setText(((DtProfesor) DtUsr).sitioWeb);
                insti = ((DtProfesor) DtUsr).institucion;
                
                Usuario Usr = sistema.getUsuario(usrKey);
                 
                if(Usr != null){
                    
                    Collection<Clase> clasesProfe = ((Profesor)Usr).getClaseDictada();
                    if (!clasesProfe.isEmpty()){
                        int i = 0;
                        String [] nomClase = new String[clasesProfe.size()];
                        for(Clase c : clasesProfe){
                            nomClase[i] = c.getNombreClase();
                            i++;
                        }
                        this.ClasesProfeCB.setModel(new DefaultComboBoxModel(nomClase));
                        this.ClasesProfeCB.setEnabled(true);
                        this.showActividadAsociada(this.ClasesProfeCB.getSelectedItem().toString(), insti);
                        
                        for (Clase c : clasesProfe){
                            if(c.getNombreClase().equals(this.ClasesProfeCB.getSelectedItem())){
                                this.nomClassTF.setText(c.getNombreClase());
                                this.fechaInicioTF.setText(c.getFecha().toString());
                                this.fechaAltaTF.setText(c.getFechaRegistro().toString());
                                this.horaInicioTF.setText(c.getHoraIni().toString());
                                if(c.getHoraFin() != null) this.horaFinTF.setText(c.getHoraFin().toString());
                                Integer minRegistros = c.getCantMin();
                                Integer maxRegistros = c.getCantMax();
                                Integer cantRegistros = c.getCantSocios();
                                this.minRegistrosTF.setText(minRegistros.toString());
                                this.maxRegistrosTF.setText(maxRegistros.toString());
                                this.cantRegistrosTF.setText(cantRegistros.toString());
                                this.urlClassTF.setText(c.getClaseURL());
                                
                                break;
                            }
                        }
                    }
                    else{
                        String [] s = new String[] {"Aun no dicta clases"};
                        this.ClasesProfeCB.setModel(new DefaultComboBoxModel(s));
                        this.ClasesProfeCB.setEnabled(false);
                    }
                }
            }
            else if(DtUsr instanceof DtSocio){
                
                ArrayList<String> claseRegistradaSocio = sistema.getClaseRegistradaSocio(((DtSocio)DtUsr));
                if(claseRegistradaSocio != null){
                    String[] claseRegSocio = new String [claseRegistradaSocio.size()];
                    int i = 0;
                    for(String s : claseRegistradaSocio){
                        claseRegSocio[i] = s;
                        i++;
                    }
                    this.clasesRegSocioCB.setModel(new DefaultComboBoxModel(claseRegSocio));
                }
                else{
                    String [] s = new String [] {"No Esta Registrado a ninguna Clase"};
                    this.clasesRegSocioCB.setModel(new DefaultComboBoxModel(s));
                }
            }
            
            Image image = null;
            try {
                    URL url = new URL(DtUsr.imagenUrl);
                    if(ImageIO.read(url) != null)
                    {
                        image = ImageIO.read(url).getScaledInstance(180, 180, 100);
                    }
            } 
            catch (IOException e) {
                e.printStackTrace();
            }
            if(image != null){
                this.jLabelImage.setIcon(new ImageIcon(image));
            }
            else this.jLabelImage.setIcon(null);

        }
        
    }//GEN-LAST:event_UsuariosjListValueChanged

    private void ClasesProfeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClasesProfeCBActionPerformed
        String clase = this.ClasesProfeCB.getSelectedItem().toString();
        this.showActividadAsociada(clase, insti);
    }//GEN-LAST:event_ClasesProfeCBActionPerformed

    private void ActividadDepoAsociadaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActividadDepoAsociadaBTActionPerformed
        System.out.println("ActividadDepoAsociadaTF pressed");
        this.jFrame1.setVisible(true);
        Fabrica f = new Fabrica();
	IControlador sistema = f.getInterface();
        
        DtActividadDeportiva acti = sistema.getDtActividadDepo(this.ActividadDepoAsociadaTF.getText());
        
        int minutes = (int) acti.duracion;
        
        int h = minutes / 60;
        int m = minutes % 60;
        
        String dur = String.format("%02d:%02d", h, m);

        this.nomActiTFJ2.setText(acti.nombreAct);
        this.descTAJ2.setText(acti.descripcion);
        this.duracionTFJ2.setText(dur);
        this.costoTFJ2.setText(String.valueOf(acti.costo));
        this.fechaRegTFJ2.setText(acti.fechaRegistro.toString());
        
        if(acti.clases != null){
            String [] c = new String[acti.clases.size()];
            int i = 0;
            for(String s : acti.clases){
                c[i] = s;
            }
            this.clasesActiJLJ2.setModel(new DefaultComboBoxModel(c));
        }
        else{
            String [] c = new String[] {""};
            this.clasesActiJLJ2.setModel(new DefaultComboBoxModel(c));
        }
        if(acti.cuponeras != null){
            String [] c = new String[acti.cuponeras.size()];
            int i = 0;
            for(String s : acti.cuponeras){
                c[i] = s;
            }
            this.cuponerasActiJLJ2.setModel(new DefaultComboBoxModel(c));
        }
        else{
            String [] c = new String[] {""};
            this.cuponerasActiJLJ2.setModel(new DefaultComboBoxModel(c));
        }
        
    }//GEN-LAST:event_ActividadDepoAsociadaBTActionPerformed

    public void showActividadAsociada(String nomClase, String Insti){
        Fabrica f = new Fabrica();
	IControlador sistema = f.getInterface();
        String acti = sistema.getActividadDepoAsociadaClase(nomClase, Insti);
        
        if(acti != null){
            this.ActividadDepoAsociadaTF.setEnabled(true);
            this.ActividadDepoAsociadaTF.setText(acti);
        }
        else{
            this.ActividadDepoAsociadaTF.setEnabled(false);
            this.ActividadDepoAsociadaTF.setText("");
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActividadDepoAsociadaBT;
    private javax.swing.JTextField ActividadDepoAsociadaTF;
    private javax.swing.JTextField ApellidoTF;
    private javax.swing.JTextArea BiografiaProfeTA;
    private javax.swing.JComboBox<String> ClasesProfeCB;
    private javax.swing.JTextArea DescripcionProfeTA;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JTextField FechaNacimientoTF;
    private javax.swing.JTextField NicknameTF;
    private javax.swing.JTextField NombeTF;
    private javax.swing.JTextField SitioWebTF;
    private javax.swing.JTextField UrlImagenTF;
    private javax.swing.JList<String> UsuariosjList;
    private javax.swing.JTextField cantRegistrosTF;
    private javax.swing.JList<String> clasesActiJLJ2;
    private javax.swing.JComboBox<String> clasesRegSocioCB;
    private javax.swing.JTextField costoTFJ2;
    private javax.swing.JList<String> cuponerasActiJLJ2;
    private javax.swing.JTextArea descTAJ2;
    private javax.swing.JTextField duracionTFJ2;
    private javax.swing.JTextField fechaAltaTF;
    private javax.swing.JTextField fechaInicioTF;
    private javax.swing.JTextField fechaRegTFJ2;
    private javax.swing.JTextField horaFinTF;
    private javax.swing.JTextField horaInicioTF;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField maxRegistrosTF;
    private javax.swing.JTextField minRegistrosTF;
    private javax.swing.JTextField nomActiTFJ2;
    private javax.swing.JTextField nomClassTF;
    private javax.swing.JTextField urlClassTF;
    // End of variables declaration//GEN-END:variables
    private String insti;
}
