/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import logica.datatypes.DtClase;
import logica.datatypes.DtCuponera;

/**
 *
 * @author progappvm
 */
public class ventanaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form ventanaConsulta
     */
    public ventanaConsulta(Object DtAUsar) {
        initComponents();
        
        if(DtAUsar.getClass().equals(DtClase.class)){
        	DtClase claseAUsar = (DtClase) DtAUsar;
        	
        	this.label1.setText("Nombre de la clase: " + claseAUsar.nombreClase);
        	this.label2.setText("Cantidad de Socios minima: " + claseAUsar.cantMin);
        	this.label3.setText("Cantidad de Socios maxima: " + Integer.toString(claseAUsar.cantMax));
        	this.label4.setText("URL: " + claseAUsar.claseURL);
        	this.label5.setText("Fecha de la clase: " + claseAUsar.fecha);
        	this.label6.setText("Fecha de Alta: " + claseAUsar.fechaRegistro);
        	this.label7.setText("Hora inicio: " + claseAUsar.horaIni);

        	
        }else {
        	DtCuponera cupoAUsar = (DtCuponera) DtAUsar;
        	
        	this.label1.setText("Nombre de la cuponera: " + cupoAUsar.nombreCup);
        	this.label2.setText("Descripcion: " + cupoAUsar.descripcion);
        	this.label3.setText("Descuento: " + cupoAUsar.descuento + "%");
        	this.label4.setText("Cantidad de clases asociadas: " + Integer.toString(cupoAUsar.cantClases));
;
        	this.label5.setText("Fecha de Inicio: " + cupoAUsar.fechaInicio);
        	this.label6.setText("Fecha de Fin: " + cupoAUsar.fechaFin);
        	this.label7.setText("Fecha de Alta: " + cupoAUsar.fechaAlta);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAzul = new javax.swing.JPanel();
        botonSalida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAzul.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        botonSalida.setBackground(new java.awt.Color(255, 51, 51));
        botonSalida.setText("<---------");
        botonSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalidaMouseClicked(evt);
            }
        });
        botonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalidaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setText("Datos de Clase/Cuponera");

        label1.setText("label1");
        
        JLabel label2 = new JLabel("label2");
        
        JLabel label3 = new JLabel("label3");
        
        JLabel label4 = new JLabel("label4");
        
        JLabel label5 = new JLabel("label5");
        
        JLabel label6 = new JLabel("label6");
        
        JLabel label7 = new JLabel("label7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(botonSalida)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabel1))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label1))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label2))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label3))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label4))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label5))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label6))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label7)))
        			.addPreferredGap(ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
        			.addComponent(panelAzul, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(panelAzul, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(label1)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(label2)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(label3)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(label4)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(label5)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(label6)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(label7)
        			.addPreferredGap(ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
        			.addComponent(botonSalida))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalidaMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_botonSalidaMouseClicked

    private void botonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ventanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ventanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ventanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ventanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ventanaConsulta().setVisible(true);
//            }
//        });
//    }
    
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label1;
    private javax.swing.JPanel panelAzul;
}
