package gui;
import logica.datatypes.DtCuponera;

import java.text.Format;
import java.util.ArrayList;

import logica.datatypes.DtClase;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.JScrollPane;
import javax.swing.JList;
import javax.swing.JLabel;

public class VentanaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsulta
     */
    public VentanaConsulta() {
        initComponents();
    }
    
    public VentanaConsulta(Object DtAUsar){
        initComponents();
        
        if(DtAUsar.getClass().equals(DtCuponera.class)) {
        	DtCuponera cupo = ((DtCuponera) DtAUsar);
        	this.labelTitulo.setText("Consulta de Cuponera");
        	this.label1.setText("Nombre :" + cupo.nombreCup);
        	this.label2.setText("Descripcion: " + cupo.descripcion);
        	this.label3.setText("Cant. clases: "+ cupo.cantClases);
        	this.label4.setText("Descuento: " + cupo.descuento + "%");
        	this.label5.setText("Fecha de Inicio: " + cupo.fechaInicio);
        	this.label6.setText("Fecha de Fin: " + cupo.fechaFin);
        	this.label7.setText("Fecha de Alta: " + cupo.fechaAlta);
        	
//        	DefaultListModel listModel;
//            
//            listModel = new DefaultListModel<>();
//            
//            for(int i = 0; i < clase.size();i++) {
//            	listModel.addElement(arrCat.get(i));
//            }

        	
        }else {
        	DtClase clase = ((DtClase) DtAUsar);
        	this.labelTitulo.setText("Consulta de Clase");
        	this.label1.setText("Nombre :" + clase.nombreClase);
        	this.label2.setText("Cantidad minima Socios: " + clase.cantMin);
        	this.label3.setText("Cantidad maxima Socios: "+ clase.cantMax);
        	this.label4.setText("Fecha " + clase.fecha );
        	this.label5.setText("Hora Inicio: " + clase.horaIni);
        	this.label6.setText("Fecha de Registro: " + clase.fechaRegistro);
        	this.label7.setText("URL: " + clase.claseURL);
        	//this.list.getListM
        	
        }
    }
    
    public VentanaConsulta(Object DtAUsar, ArrayList<String> arrCat){
        initComponents();
        
        	DtCuponera cupo = ((DtCuponera) DtAUsar);
        	this.labelTitulo.setText("Consulta de Cuponera");
        	this.label1.setText("Nombre :" + cupo.nombreCup);
        	this.label2.setText("Descripcion: " + cupo.descripcion);
        	this.label3.setText("Cant. clases: "+ cupo.cantClases);
        	this.label4.setText("Descuento: " + cupo.descuento + "%");
        	this.label5.setText("Fecha de Inicio: " + cupo.fechaInicio);
        	this.label6.setText("Fecha de Fin: " + cupo.fechaFin);
        	this.label7.setText("Fecha de Alta: " + cupo.fechaAlta);
        	
        	DefaultListModel listModel;
            
            listModel = new DefaultListModel<>();
            
            for(int i = 0; i < arrCat.size();i++) {
            	listModel.addElement(arrCat.get(i));
            }
            this.list.setModel(listModel);
        	
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAzul = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        botonSalida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAzul.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelTitulo.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        labelTitulo.setText("titulo");

        label1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label1.setText("jLabel2");

        label2.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label2.setText("jLabel3");

        label3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label3.setText("jLabel4");

        label4.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label4.setText("jLabel5");

        label5.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label5.setText("jLabel6");

        label6.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label6.setText("jLabel7");

        label7.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        label7.setText("jLabel8");

        botonSalida.setBackground(new java.awt.Color(255, 51, 51));
        botonSalida.setText("<---------");
        botonSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalidaMouseClicked(evt);
            }
        });
        botonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalidaActionPerformed(evt);
            }
        });
        
        JScrollPane scrollPane = new JScrollPane();
        
        lblNewLabel = new JLabel("Categorias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(labelTitulo))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label1))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label2))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label3))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label4))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label5))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label6))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label7))
        				.addComponent(botonSalida)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 186, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblNewLabel)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(panelAzul, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(panelAzul, GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(6)
        			.addComponent(labelTitulo)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(label1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(label2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(label3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(label4)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(label5)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(label6)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(label7)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(botonSalida))
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(260, Short.MAX_VALUE)
        			.addComponent(lblNewLabel)
        			.addGap(77))
        );
        
        list = new JList();
        scrollPane.setViewportView(list);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalidaMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_botonSalidaMouseClicked

    private void botonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalidaActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaConsulta().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalida;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelAzul;
    private JLabel lblNewLabel;
    private JList list;
}
